# Generated by Django 3.2.7 on 2021-11-03 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='nonce',
            field=models.CharField(default='Hly0pB1V3XE0gLWmEYZaZeB2BvsSjoYJBi8O1OBi2gb1tCxp8v', max_length=50),
        ),
    ]
