# Generated by Django 3.2.9 on 2021-11-17 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='smartcontract',
            old_name='created_by',
            new_name='owner',
        ),
    ]
