# Generated by Django 3.2.9 on 2021-12-08 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clause',
            name='content',
            field=models.TextField(blank=True, default='placeholder for clause content'),
        ),
    ]
