# Generated by Django 3.2.9 on 2021-12-12 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0002_alter_clause_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='clause',
            name='color',
            field=models.CharField(blank=True, max_length=7),
        ),
    ]
