import ConnectWithWallet from '@/components/ConnectWithWallet'
import Layout from '@/components/Layout'
import Head from 'next/head'
import Image from 'next/image'
// import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <>
      <Head>
        <title>home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <section>
        <h2>homepage</h2>
      </section>
    </>
  )
}
