# Generated by Django 3.2.7 on 2021-10-29 04:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('posts', '0001_initial'),
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='postAuthor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.profile'),
        ),
        migrations.AddField(
            model_name='posts',
            name='postComments',
            field=models.ManyToManyField(blank=True, related_name='comments', to='profiles.Profile'),
        ),
        migrations.AddField(
            model_name='posts',
            name='postLikes',
            field=models.ManyToManyField(blank=True, related_name='likes', to='profiles.Profile'),
        ),
        migrations.AddField(
            model_name='posts',
            name='postReposts',
            field=models.ManyToManyField(blank=True, related_name='retweets', to='profiles.Profile'),
        ),
        migrations.AddField(
            model_name='postlikes',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.profile'),
        ),
        migrations.AddField(
            model_name='postlikes',
            name='post_identifier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.posts'),
        ),
    ]
