# Generated by Django 3.2.9 on 2021-11-10 04:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid
import wallets.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('address', models.CharField(max_length=42, unique=True, validators=[wallets.validators.ethereumAddressValidator])),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nonce', models.CharField(default='DJ7bTTiHl74XRsxqQjdshRhb3v3Jd3p8xayA8sVS4lJANWsCEh', max_length=50)),
                ('ens', models.CharField(blank=True, max_length=200, null=True, unique=True, validators=[wallets.validators.ensDomainValidator])),
                ('verified', models.BooleanField(default=False)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
