# Generated by Django 3.2.9 on 2021-11-10 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='nonce',
            field=models.CharField(default='7ZAclG7Zj1Xa8spx9o7zDdfdU223Q1E7hAxygmt1qMXVvuD2Hx', max_length=50),
        ),
    ]
