# Generated by Django 3.2.9 on 2021-11-17 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0003_alter_wallet_nonce'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='nonce',
            field=models.CharField(default='2lbPWzrBZabNYKnNi4fvB2GJs2BQh52uOIf9ZP9eUe2dvMGSe3', max_length=50),
        ),
    ]
