# Generated by Django 3.2.9 on 2021-11-17 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0004_alter_wallet_nonce'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='nonce',
            field=models.CharField(default='2P8mwqZl6TUptDA6QA7Y7RHooz8fOySDWRMSODajvSYi8lwy5n', max_length=50),
        ),
    ]
