# Generated by Django 3.2.9 on 2021-11-17 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0005_alter_wallet_nonce'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='nonce',
            field=models.CharField(default='ODoyOTCk7fEWIlCAXGoIMlQ6ZhT0gWCcqYqRnO6RQConwxovbE', max_length=50),
        ),
    ]
