# Generated by Django 3.2.9 on 2021-11-17 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0006_alter_wallet_nonce'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='nonce',
            field=models.CharField(default='5KZPkteAdCWiaEDasGDKfTOEgnyTuRsx4uemqzcarvou4FTqV9', max_length=50),
        ),
    ]
