# Generated by Django 3.2.9 on 2021-11-17 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0007_alter_wallet_nonce'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='nonce',
            field=models.CharField(default='TqsqKQVXLeJLnHAW82eoPoWRThB1Jz4C1kYL0bSND98VdeBzEV', max_length=50),
        ),
    ]
