# Generated by Django 3.2.9 on 2021-11-29 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0008_alter_wallet_nonce'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='nonce',
            field=models.CharField(default='Ixnmn2uBsjBCq8FCROWyOzCJ1UjAjV5V85QwvrmzeTLMq3QwJZ', max_length=50),
        ),
    ]
