# Generated by Django 3.2.9 on 2021-11-29 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0009_alter_wallet_nonce'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='nonce',
            field=models.CharField(default='JiT2Aj5nzgoKTJSGL5TXzQdHbWnNf10eh6Obyq9g4bUfmmzrKx', max_length=50),
        ),
    ]
