# Generated by Django 3.2.9 on 2021-12-08 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0010_alter_wallet_nonce'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='nonce',
            field=models.CharField(default='kMVsP3OzxLdvTZAOV1rPhtjrg69KgfFVB6FvNijCIxUi0FCupO', max_length=50),
        ),
    ]
