# Generated by Django 3.2.9 on 2021-12-08 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0011_alter_wallet_nonce'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='nonce',
            field=models.CharField(default='p4bjg3a5DsfuqrLqdz0XoxHC2PshnBVnu7a1Poa3VcYEi6JadT', max_length=50),
        ),
    ]
