# Generated by Django 3.2.9 on 2021-12-12 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0012_alter_wallet_nonce'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='nonce',
            field=models.CharField(default='Owo4TUYbhRUzv95N4fzjOuO8z75KYsbfjPptjEFRIsxTZvLL7q', max_length=50),
        ),
    ]
