# Generated by Django 3.2.9 on 2021-12-12 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0013_alter_wallet_nonce'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='nonce',
            field=models.CharField(default='5A6pNm7Wt4vTX9oN3GODfBbHRZwZDsGq1kAeM0TMmgSSOxTsYe', max_length=50),
        ),
    ]
