# Generated by Django 3.2.7 on 2022-03-22 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0014_alter_wallet_nonce'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='nonce',
            field=models.CharField(default='v1bzp50SFRugjZvI7rjZnlrAVX1YQEbznwEMip3YVIyPLV2OIE', max_length=50),
        ),
    ]
